export const weekTempList = [
  {
    id: 0,
    day: 'Завтра',
    date: '',
    month: '',
    imgUrl: './images/weather/foggy.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 1,
    day: 'Пн,',
    date: '15',
    month: 'мар',
    imgUrl: './images/weather/rainy.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 2,
    day: 'Вт,',
    date: '16',
    month: 'мар',
    imgUrl: './images/weather/rainy.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 3,
    day: 'Ср,',
    date: '17',
    month: 'мар',
    imgUrl: './images/weather/thunder.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 4,
    day: 'Чт,',
    date: '18',
    month: 'мар',
    imgUrl: './images/weather/thunder.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 5,
    day: 'Пт,',
    date: '19',
    month: 'мар',
    imgUrl: './images/weather/thunder.svg',
    maxTemp: 10,
    minTemp: 4,
  },
  {
    id: 6,
    day: 'Сб,',
    date: '20',
    month: 'мар',
    imgUrl: './images/weather/thunder.svg',
    maxTemp: 10,
    minTemp: 4,
  },
];
export const hoursTempList = [
  {
    id: 0,
    time: '15:00',
    imgUrl: './images/weather/foggy.svg',
    temp: 10,
  },
  {
    id: 1,
    time: '16:00',
    imgUrl: './images/weather/foggy.svg',
    temp: 10,
  },
  {
    id: 2,
    time: '17:00',
    imgUrl: './images/weather/foggy.svg',
    temp: 10,
  },
  {
    id: 3,
    time: '18:00',
    imgUrl: './images/weather/foggy.svg',
    temp: 10,
  },
  {
    id: 4,
    time: '19:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 5,
    time: '20:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 6,
    time: '21:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 7,
    time: '22:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 9,
    time: '23:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 10,
    time: '00:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 11,
    time: '01:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
  {
    id: 12,
    time: '02:00',
    imgUrl: './images/weather/thunder.svg',
    temp: 10,
  },
];
